# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

title: Act On Mass
url: https://actonmass.org
collections:
  issues:
    output: true
    permalink: :collection/:name/
  legislators:
    output: true
    permalink: :collection/:name/
  bills:
    output: true
    permalink: :collection/:name/
  committees:
    output: false
  districts:
    output: false
  bill_events:
    output: false
defaults:
  - scope:
      path: ""
      type: "legislators"
    values:
      layout: "legislator"
  - scope:
      path: ""
      type: "bills"
    values:
      layout: "bill"
  - scope:
      path: ""
      type: "issues"
    values:
      layout: "issue"
permalink: /post/:year/:month/:day/:title # for blog posts
paginate: 12
paginate_path: "/blog/:num/"
excerpt_separator: <!--more-->
include: ["_pages", "_redirects"]
exclude:
  - README.md
  - .circleci
  - vendor
  - node_modules
  - src
  - .ts-dist
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
