# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

title: Act On Mass
url: https://next.actonmass.org

menu:
  - title: Home
    page: /
  - title: The pledge
    page: /pledge
  - title: About us
    page: /about-us
  - title: Issues
    page: /#issues
  - title: Latest updates
    page: /blog
footer:
  - title: Donate
    page: https://secure.actblue.com/donate/act-on-mass
  - title: About us
    page: /about-us
  - title: FAQs
    page: /faq
  - title: Privacy Policy
    page: /privacy
donate_button_url: https://secure.actblue.com/donate/act-on-mass

permalink: /post/:year/:month/:day/:title  # for blog posts

paginate: 10
paginate_path: "/blog/:num/"
excerpt_separator: <!--more-->
include: ['_pages']
exclude:
  - README.md
  - .circleci
  - vendor
plugins:
  - jekyll-paginate
