# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

title: Act On Mass
url: https://actonmass.org
description: Act on Mass is a non-profit organization that tracks what happens in the Massachusetts State House and what issues matter to you.

menu:
  - title: Home
    page: /
  - title: The pledge
    page: /pledge
  - title: About us
    page: /about-us
  - title: Issues
    page: /#issues
  - title: Latest updates
    page: /blog
footer:
  - title: Donate
    page: https://secure.actblue.com/donate/act-on-mass
  - title: About us
    page: /about-us
  - title: FAQs
    page: /faq
  - title: Privacy Policy
    page: /privacy
donate_button_url: https://secure.actblue.com/donate/aom-q4-web

collections:
  issues:
    output: true
permalink: /post/:year/:month/:day/:title # for blog posts
paginate: 10
paginate_path: "/blog/:num/"
excerpt_separator: <!--more-->
include: ["_pages", "_redirects"]
exclude:
  - README.md
  - .circleci
  - vendor
  - node_modules
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
