# CircleCI 2.0 configuration file. See <https://circleci.com/docs/2.0/language-ruby/>.
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2-node-browsers # use the browsers variant image to have Java preinstalled as it is a dependency of html5validator

    steps:
      - checkout
      - restore_cache:
          key: general-cache-v1
      - restore_cache:
          key: ruby-cache-{{ checksum "Gemfile" }}
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}

      - run:
          name: Update bundler
          command: gem install bundle

      - run:
          name: Install Ruby dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Install Node dependencies
          command: yarn

      - run:
          name: Install html5validator
          command: |
            sudo apt-get update
            sudo apt-get install -y python-pip
            pip install --user --upgrade html5validator  # will install in $HOME/.local

      - save_cache:
          key: general-cache-v2
          paths:
            - $HOME/.local

      - save_cache:
          key: ruby-cache-{{ checksum "Gemfile" }}
          paths:
            - ./vendor/bundle

      - save_cache:
          key: node-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Check Jekyll configuration
          command: bundle exec jekyll doctor

      - run:
          name: Compile website
          command: yarn build

      - run:
          name: Check homepage was compiled
          command: test -s _site/index.html

      - run:
          name: Check HTML common mistakes
          command: bundle exec htmlproofer ./_site --assume-extension --check-html --disable-external --empty-alt-ignore --check-img-http

      - run:
          name: Validate HTML spec compliance
          command: echo "Skipping HTML validation for now"
          # command: $HOME/.local/bin/html5validator --root _site --ignore iframe

      - run:
          name: Start server
          command: bundle exec jekyll serve --no-watch --skip-initial-build
          background: true
      - run:
          name: Wait for server to start
          command: |
            while ! curl --silent http://localhost:4000
            do sleep 1
            done
