url: https://actonmass.org
donate_button_url: https://secure.actblue.com/donate/aom2023-q3-web
description: Act on Mass is a non-profit organization that tracks what happens
  in the Massachusetts State House and the issues that matter to you.
cta:
  active: true
  title: "Fall Fundraiser: Have your donation MATCHED today!"
  href: https://secure.actblue.com/donate/aom2023-fallfundraiser?refcode=CTA
menu:
  - href: /about-us
    title: About Us
initiatives_menu:
  - href: /sunlight-agenda
    title: Sunlight Agenda
  - href: /the-campaign
    title: The People's House Campaign
  - href: /right2strike
    title: Right to Strike
  - href: /pledge
    title: Voters Deserve To Know Pledge
learn_more_menu:
  - href: /bills
    title: Bills
  - href: /#issues
    title: Issues
  - href: /legislator-search
    title: Legislator Search
  - href: https://secure.everyaction.com/1iWRboEfXUyjUvBt5HMoZw2
    title: Saturday Scoop
  - href: /blog
    title: Blog
  - href: /news
    title: News & Media
footer:
  - title: FAQs
    href: /faq
  - title: Privacy Policy
    href: /privacy
  - href: https://secure.everyaction.com/1iWRboEfXUyjUvBt5HMoZw2
    title: Subscribe to the Saturday Scoop
  - title: CONTACT US
    href: info@actonmass.org
