url: https://actonmass.org
donate_button_url: https://secure.actblue.com/donate/aom2022-q2-web
description: Act on Mass is a non-profit organization that tracks what happens
  in the Massachusetts State House and the issues that matter to you.
cta:
  active: true
  title: Sign up for our 2022 Ballot Campaign
  href: https://secure.everyaction.com/p/O114QFmSd0qUkDCj0odNSA2?results=True&date_start=04-27-2021
menu:
  - href: /about-us
    title: About Us
initiatives_menu:
  - href: /the-campaign
    title: The People's House Campaign
  - href: /right2strike
    title: Right to Strike
  - href: /pledge
    title: Voters Deserve To Know Pledge
learn_more_menu:
  - href: /bills
    title: Bills
  - href: /#issues
    title: Issues
  - href: /legislator-search
    title: Legislator Search
  - href: /endorsements-2022
    title: Endorsements
  - href: /blog
    title: Blog
  - href: /news
    title: News & Media
footer:
  - title: FAQs
    href: /faq
  - title: Privacy Policy
    href: /privacy
