url: https://actonmass.org
donate_button_url: https://secure.actblue.com/donate/aom2021-q2-web
description:
  Act on Mass is a non-profit organization that tracks what happens in the Massachusetts State House
  and what issues matter to you.
menu:
  - href: /about-us
    title: About Us
  - href: /the-campaign
    title: The Campaign
  - href: /right2strike
    title: Right to Strike
  - href: /pledge
    title: The Pledge
learn_more_menu:
  - href: /bills
    title: Bills
  - href: /#issues
    title: Issues
  - href: /legislator-search
    title: Legislator Search
  - href: /blog
    title: Blog
footer:
  - title: FAQs
    href: /faq
  - title: Privacy Policy
    href: /privacy
