url: https://actonmass.org
donate_button_url: https://secure.everyaction.com/_SjkDwX4y0uDuoc24BFq4w2
description: Act on Mass is a non-profit organization that tracks what happens
  in the Massachusetts State House and the issues that matter to you.
cta:
  active: true
  title: Come to our Transparency on Tour Collaborative Launch! May 26th
  href: https://secure.everyaction.com/i7AQ8Yz8c0u659qdSnsKug2
menu:
  - href: /about-us
    title: About Us
initiatives_menu:
  - href: /good-government-agenda
    title: Good Government Agenda
  - href: /sunlight-agenda
    title: Sunlight Agenda
  - href: /the-campaign
    title: The People's House Campaign
  - href: /pledge
    title: Voters Deserve To Know Pledge
learn_more_menu:
  - href: /bills
    title: Bills
  - href: /#issues
    title: Issues
  - href: /legislator-search
    title: Legislator Search
  - href: https://secure.everyaction.com/1iWRboEfXUyjUvBt5HMoZw2
    title: Saturday Scoop
  - href: /blog
    title: Saturday Scoop Archive & Blog
  - href: /news
    title: News & Media
  - href: /LTE
    title: Writing a Letter to the Editor
  - href: /transparency
    title: Transparency in the State House
  - href: /ballot-question
    title: Transparency Ballot Question 2020 & 2022
footer:
  - title: FAQs
    href: /faq
  - title: Privacy Policy
    href: /privacy
  - href: https://secure.everyaction.com/1iWRboEfXUyjUvBt5HMoZw2
    title: Subscribe to the Saturday Scoop
  - title: CONTACT US
    href: /contact
