backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: 'img'
collections:
  - name: 'blog'
    label: 'Blog post'
    sort: 'date:desc'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - label: Redirect from
        name: redirect_from
        required: false
        widget: list
        collapsed: false
        field:
          label: Redirection
          name: redirection
          widget: string
          default: "Example: /covid"
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
