backend:
  name: git-gateway
  branch: next
local_backend: true
# publish_mode: editorial_workflow  # Deactivate on next since we are still collection data and don't want to go through a PR for each change
media_folder: "img"
collections:
  - name: blog
    label: Blog post
    sort: "date:desc"
    folder: _posts/
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: post
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Redirect from
        name: redirect_from
        required: false
        widget: list
        collapsed: false
        field:
          label: Redirection
          name: redirection
          widget: string
          default: "Example: /covid"
      - label: Image
        name: image
        widget: image
        required: false
      - label: Body
        name: body
        widget: markdown
  - name: issues
    label: Issues
    folder: _issues/
    create: true
    slug: "{{title}}"
    editor:
      preview: false
    fields:
      - &id-field
        label: ID
        name: aom_id
        widget: string
      - name: ocd_id
        widget: hidden
      - label: Layout
        name: layout
        widget: hidden
        default: issue
      - label: Title
        name: title
        widget: string
      - label: Subtitle
        name: subtitle
        widget: string
        required: false
      - label: Logo
        name: logo
        widget: string
        required: false
      - label: Homepage image
        name: img
        widget: image
        required: false
      - label: Catchphrase
        hint: Appears on the headline
        name: catchphrase
        widget: string
        required: false
      - label: Issue page image
        name: page_img
        widget: image
        required: false
      - label: Bills section title
        hint: Completes the sentence "Bills to support..."
        name: bills_to_support_title
        widget: string
        required: false
      - label: Bill
        name: highlighted_bills
        widget: relation
        collection: bills
        multiple: true
        searchFields:
          - title
        displayFields:
          - title
        valueField: aom_id
      - label: “Failures“ section title
        name: failures_block_title
        widget: string
        required: false
      - label: Failures
        name: failures
        required: false
        collapsed: false
        widget: list
        fields:
          - label: Title
            name: title
            required: true
            widget: string
          - label: Text
            name: text
            required: true
            widget: markdown
      - label: Questions
        name: questions
        required: false
        collapsed: true
        widget: list
        fields:
          - label: Question
            name: title
            required: true
            widget: string
          - label: Answer
            name: text
            required: true
            widget: markdown
      - label: Learn more links
        name: learn_more
        required: false
        collapsed: true
        widget: list
        fields:
          - label: Title
            name: title
            required: true
            widget: string
          - label: Image
            name: img
            required: false
            widget: image
          - label: Answer
            name: link
            required: false
            widget: string
      - label: References
        name: references
        required: false
        collapsed: true
        widget: list
        fields:
          - label: "Key"
            hint: Can be used to add a link to the reference
            name: key
            required: true
            widget: string
          - label: Title
            name: title
            required: true
            widget: string
          - label: Link
            name: link
            required: false
            widget: string
      - label: Order
        name: order
        widget: number
        valueType: int
        required: false
  - name: legislators
    label: Legislators
    folder: _legislators/
    create: true
    slug: "{{first_name}}-{{last_name}}"
    identifier_field: last_name
    editor:
      preview: false
    fields:
      - <<: *id-field
        default: "Exemple: nika-elugardo"
      - label: First name
        name: first_name
        widget: string
      - label: Last name
        name: last_name
        widget: string
      - label: District
        name: district
        widget: relation
        collection: districts
        searchFields: [name]
        displayFields: [name]
        valueField: aom_id
      - label: Party
        name: party
        widget: select
        options:
          - label: Democrat
            value: D
          - label: Republican
            value: R
      - label: Phone number
        name: phone
        widget: string
        required: false
      - label: Email
        name: email
        widget: string
        required: false
      - label: Hometown
        name: hometown
        widget: string
        required: false
      - label: Picture
        name: picture
        widget: string
        required: false
      - label: Square Picture
        name: square_picture
        widget: string
        required: false
      - &date-picker
        label: End date
        name: end_date
        required: false
        widget: datetime
        format: YYYY-MM-DD
        timeFormat: false
        default: null
      - <<: *date-picker
        label: Start date
        name: start_date
        required: false
      - label: malegislature.gov URL
        name: malegislature_url
        widget: string
        required: false
      - label: Website
        name: website
        widget: string
        required: false
      - label: Facebook page
        name: facebook
        widget: string
        required: false
      - label: Twitter account
        name: twitter
        widget: string
        pattern:
          - '^([\w]+)$'
          - 'Username only: don''t include the "http" prefix or the "@"'
        required: false
        hint: 'Username only: don''t include the "http" prefix or the "@"'
  - name: districts
    label: Districts
    folder: _districts/
    create: true
    slug: "{{chamber}}-{{name}}"
    identifier_field: name
    editor:
      preview: false
    fields:
      - <<: *id-field
        default: "Exemple: house-27th-middlesex"
      - label: Name
        name: name
        widget: string
      - label: Chamber
        name: chamber
        widget: select
        options:
          - label: House
            value: house
          - label: Senate
            value: senate
      - label: Van ID
        name: van_id
        widget: string
        required: false
      - label: Latitude
        name: lat
        widget: number
        valueType: float
        required: false
      - label: Longitude
        name: lng
        widget: number
        valueType: float
        required: false
  - name: committees
    label: Committees
    folder: _committees/
    create: true
    slug: "{{chamber}}-{{name}}"
    identifier_field: title
    editor:
      preview: false
    fields:
      - <<: *id-field
        default: "Exemple: joint-rules"
      - label: Title
        name: title
        widget: string
      - label: Chamber
        name: chamber
        widget: select
        options:
          - label: House
            value: house
          - label: Senate
            value: senate
          - label: Joint
            value: joint
      - &legislator-picker
        label: House Chair
        name: house_chair
        required: false
        widget: relation
        collection: legislators
        searchFields:
          - last_name
        valueField: aom_id
        displayFields:
          - last_name
      - <<: *legislator-picker
        label: House Vice-chair
        name: house_vice_chair
        required: false
      - <<: *legislator-picker
        label: Senate Chair
        name: senate_chair
        required: false
      - <<: *legislator-picker
        label: Senate Vice-chair
        name: senate_vice_chair
        required: false
      - <<: *legislator-picker
        label: House Members
        name: house_members
        required: false
        multiple: true
      - <<: *legislator-picker
        label: Senate Members
        name: senate_members
        multiple: true
      - label: malegislature.gov URL
        name: malegislature_url
        widget: string
        required: false
  - name: bills
    label: Bills
    folder: _bills/
    create: true
    slug: "{{title}}"
    identifier_field: title
    editor:
      preview: false
    fields:
      - <<: *id-field
        default: "Exemple: safe-communities-act"
      - label: Short title
        name: title
        widget: string
      - label: Full title
        name: full_title
        required: false
        widget: string
      - label: Article
        name: article
        required: false
        widget: string
      - label: House bill number
        name: house_no
        required: false
        widget: string
      - label: House bill link
        name: house_link
        required: false
        widget: string
      - label: Senate bill number
        name: senate_no
        required: false
        widget: string
      - label: Senate bill link
        name: senate_link
        required: false
        widget: string
      - label: Committee
        name: committee
        required: false
        widget: relation
        collection: committees
        searchFields:
          - title
        displayFields:
          - title
        valueField: aom_id
      - label: Issue
        name: issue
        required: false
        widget: relation
        collection: issues
        searchFields:
          - title
        displayFields:
          - title
        valueField: aom_id
      - label: Image
        name: img
        widget: image
        required: false
      - label: Summary bullet-points
        name: summary
        required: false
        widget: list
        collapsed: false
        field:
          label: Bullet point
          name: point
          widget: string
      - label: Organisations
        name: orgs
        required: false
        widget: list
        collapsed: false
        field:
          label: Org
          name: org
          widget: string
      - <<: *legislator-picker
        label: House lead sponsors
        name: house_lead_sponsors
        multiple: true
        required: false
      - <<: *legislator-picker
        label: Senate lead sponsors
        name: senate_lead_sponsors
        multiple: true
        required: false
      - <<: *legislator-picker
        label: Co-sponsors
        name: co_sponsors
        multiple: true
        required: false
      - label: Bill history events
        name: history
        required: false
        collapsed: false
        widget: list
        fields:
          - label: Detailed bill event
            name: bill_event
            required: false
            widget: relation
            collection: bill_events
            valueField: aom_id
            searchFields:
              - id
            displayFields:
              - id
          - <<: *date-picker
            required: false
            label: Date
            hint: Fill only if there is no detailed bill event
            name: date
          - label: Description
            hint: Fill only if there is no detailed bill event
            required: false
            name: description
            widget: text
          - label: Type of event
            hint: Fill only if there is no detailed bill event
            required: false
            name: type
            widget: select
            options:
              - label: Normal
                value: ""
              - label: Death
                value: death
      - label: Bill timeline events
        name: timeline
        required: false
        collapsed: false
        widget: list
        fields:
          - <<: *date-picker
            required: false
            label: Date
            name: date
          - label: Description
            required: false
            name: description
            widget: string
  - name: bill_events
    path: "{{bill}}/{{description}}"
    label: Detailed bill events
    folder: _bill_events/
    create: true
    slug: "{{description}}"
    identifier_field: description
    editor:
      preview: false
    fields:
      - <<: *id-field
        default: "Exemple: safe-communities-act-2016-budget-drama"
      - <<: *date-picker
        label: Date
        name: date
      - label: Description
        name: description
        widget: text
      - label: Bill
        name: bill
        widget: relation
        collection: bills
        searchFields:
          - title
        displayFields:
          - title
        valueField: aom_id
      - label: Progressive vote
        name: progressive_vote
        widget: select
        options:
          - label: Yes
            value: yes
          - label: No
            value: no
      - label: Type of event
        hint: Different types of events render event in history
        required: false
        name: type
        widget: select
        options:
          - label: Normal
            value: ""
          - label: Death
            value: death
      - label: Vote descriptions
        name: vote_descriptions
        widget: object
        fields:
          - label: Yes vote description
            name: "yes"
            widget: string
            hint: >-
              Example: Voted to send the [Safe Communities
              Act](/bills/safe-communities-act/) to study
          - label: No vote description
            name: "no"
            widget: string
            hint: >-
              Example: Voted against sending the [Safe Communities
              Act](/bills/safe-communities-act/) to study
          - label: Unknown vote description
            name: unk
            widget: string
            hint: >-
              Example: Won't tell us how they voted on the [Safe Communities
              Act](/bills/safe-communities-act/) in committee
      - label: Votes
        name: votes
        widget: list
        collapsed: false
        fields:
          - <<: *legislator-picker
            label: Legislator
            name: legislator
          - label: Vote
            name: vote
            widget: select
            options:
              - label: "Yes"
                value: "yes"
              - label: "No"
                value: "no"
              - label: Unknown
                value: unk
  - name: "site_data"
    label: "Other data"
    editor:
      preview: false
    files:
      - label: "Pledge signatories"
        name: "pledge_signatories"
        file: "_data/pledge_signatories.yml"
        fields:
          - label: House signatories
            name: house
            widget: list
            collapsed: false
            field:
              <<: *legislator-picker
              label: Rep
              name: rep
          - label: Senate signatories
            name: senate
            widget: list
            collapsed: false
            field:
              <<: *legislator-picker
              label: Senator
              name: senator
      - &script
        label: "Pledge scripts"
        name: "pledge_scripts"
        file: "_data/pledge_scripts.yml"
        fields:
          - label: Tweet - Request
            name: tweet_request
            widget: text
          - label: Tweet - Thank you
            name: tweet_thanks
            widget: text
          - label: Call script - Request
            name: call_request
            widget: markdown
          - label: Call script - Thank you
            name: call_thanks
            widget: markdown
          - label: Tweet - After request call
            name: tweet_after_request_call
            widget: text
          - label: Tweet - After thank you call
            name: tweet_after_thanks_call
            widget: text
          - &email
            label: Email script - Request
            name: email_request
            widget: object
            fields:
              - label: Subject
                name: subject
                widget: string
              - label: Body
                name: body
                widget: markdown
          - <<: *email
            label: Email script - Thank you
            name: email_thanks
            widget: object
          - label: Tweet - After request email
            name: tweet_after_request_email
            widget: text
          - label: Tweet - After thank you email
            name: tweet_after_thanks_email
            widget: text
      - <<: *script
        label: "Default bill scripts"
        name: "default_bill_scripts"
        file: "_data/default_bill_scripts.yml"
