type IssueTextBlock {
  title: String
  text: String
}

type IssueReference {
  key: String
  title: String
  link: String
}

type IssueLearnMore {
  title: String
  img: String
  link: String
}

type Issue implements Node @dontInfer {
  aom_id: String!
  subtitle: String
  img: String
  logo: String
  title: String
  page_img: String
  catchphrase: String
  text: String
  failures_block_title: String
  bills_to_support_title: String
  highlighted_bills: [Bill] @link
  learn_more: [IssueLearnMore]!
  references: [IssueReference]!
  failures: [IssueTextBlock]!
  questions: [IssueTextBlock]!
  order: Int

  # Common calculated
  fileName: String!
  href: String!
}

type Legislator implements Node @dontInfer {
  aom_id: String!
  first_name: String!
  last_name: String!
  party: String!
  phone: String
  email: String
  hometown: String
  href: String
  square_picture: String
  malegislature_url: String
  website: String
  facebook: String
  ocd_id: String
  twitter: String
  district: District @link
  supports_the_campaign: Boolean!
  pledge: Boolean!
  start_date: String!
  end_date: String!

  # Calculated
  chamber: String!

  # Common calculated
  fileName: String!
  href: String!
}

type District implements Node @dontInfer {
  aom_id: String!
  chamber: String!
  lat: Float
  lng: Float
  name: String
  van_id: String

  # Common calculated
  fileName: String!
  href: String!
}

type Bill implements Node @dontInfer {
  aom_id: String!

  title: String
  full_title: String
  twitter_bill_name: String
  article: String
  house_no: String
  house_link: String
  senate_no: String
  senate_link: String
  committee: String
  issue: String
  img: String
  summary: [String]
  orgs: [String]
  house_lead_sponsors: [String] # TODO: link
  senate_lead_sponsors: [String] # TODO: link
  co_sponsors: [String] # TODO: link
  # scripts
  # timeline
  # votes
  # scripts_com_vote
  # history

  # Common calculated
  fileName: String!
  href: String!
}
